import * as path from "node:path";
import * as fs from "node:fs";
import type { ImpactReport } from "./impact.js";
import type { SymbolChange } from "./detector.js";
import type { SyncState } from "../sync-state.js";
import { loadSyncState, saveSyncState } from "../sync-state.js";
import { safeWrite, safeRead, mkdirp, hashContent, listDir } from "../utils/fs.js";

export interface ConflictReport {
  hasConflict: boolean;
  conflicts: { spec: string; reason: string }[];
}

const AUTO_GENERATED_MARKER = "Auto-generated by sdd-exoskeleton";

/**
 * Convert a file basename (without extension) to a PascalCase symbol name.
 * Replicates detector.ts::fileNameToSymbol to keep the module self-contained.
 */
function fileNameToSymbol(filePath: string): string {
  const baseName = path.basename(filePath, path.extname(filePath));
  return baseName
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Infer the source file path for a given SymbolChange by searching
 * `src/<module>/` for a file whose name maps to the change's symbol name.
 * Also handles the case where `src/<module>` is itself a file (e.g. `src/index`).
 * Returns null if no matching file is found.
 */
function inferFilePath(
  change: SymbolChange,
  projectDir: string,
): string | null {
  const module = change.module;
  if (!module) return null;

  const modulePath = path.join(projectDir, "src", module);

  // Check what kind of filesystem entry src/<module> is
  let stats: fs.Stats;
  try {
    stats = fs.statSync(modulePath);
  } catch {
    return null;
  }

  // Case 1: src/<module> is directly a file (e.g. src/index)
  if (stats.isFile()) {
    return modulePath;
  }

  // Case 2: src/<module> is a directory (e.g. src/auth)
  if (stats.isDirectory()) {
    const entries = listDir(modulePath);
    if (entries.length === 0) return null;

    const lowerName = change.name.toLowerCase();
    const extensions = [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"];

    // Try direct lowercase match with common extensions
    for (const ext of extensions) {
      const candidate = `${lowerName}${ext}`;
      if (entries.includes(candidate)) {
        return path.join(modulePath, candidate);
      }
    }

    // Fall back to symbol-name matching for kebab-case / snake_case filenames
    for (const entry of entries) {
      const ext = path.extname(entry);
      if (!extensions.includes(ext)) continue;
      const symbolFromFile = fileNameToSymbol(entry);
      if (symbolFromFile === change.name) {
        return path.join(modulePath, entry);
      }
    }
  }

  return null;
}

/**
 * Create an OpenSpec change folder under `openspec/changes/<timestamp>-sync/`
 * with a `proposal.md` summarising the impact report.
 *
 * Returns the absolute path to the change folder.
 */
export function generateDelta(
  impact: ImpactReport,
  projectDir: string,
): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const changeFolderName = `${timestamp}-sync`;
  const changeDir = path.join(
    projectDir,
    "openspec",
    "changes",
    changeFolderName,
  );

  mkdirp(changeDir);

  const formatList = (items: string[]): string =>
    items.length > 0
      ? items.map((item) => `- ${item}`).join("\n")
      : "- (none)";

  const moduleList = formatList(impact.affectedModules);
  const specList = formatList(impact.affectedSpecs);

  const changeList =
    impact.changes.length > 0
      ? impact.changes
          .map((c) => `- **${c.name}** (${c.type}): ${c.summary}`)
          .join("\n")
      : "- (none)";

  const proposal = [
    `# Sync Change: ${timestamp}`,
    "",
    `> ${AUTO_GENERATED_MARKER}`,
    "",
    "## Summary",
    "",
    impact.summary,
    "",
    `## Impact Level: ${impact.impactLevel}`,
    "",
    "## Affected Modules",
    "",
    moduleList,
    "",
    "## Affected Specs",
    "",
    specList,
    "",
    "## Changes",
    "",
    changeList,
    "",
  ].join("\n");

  safeWrite(path.join(changeDir, "proposal.md"), proposal);

  return changeDir;
}

/**
 * Update sync-state.json with new hashes for the affected modules.
 *
 * For each SymbolChange, the source file path is inferred from module + name,
 * the file content is hashed, and the corresponding SyncEntry is updated
 * with the new hash and timestamp. Existing `mappedSpecs` and
 * `mappedObsidianNodes` are preserved when present.
 */
export function updateSyncState(
  projectDir: string,
  changes: SymbolChange[],
  _currentRef: string,
): void {
  const syncState = loadSyncState(projectDir);
  const now = new Date().toISOString();

  // Build new entries object (immutable)
  const newEntries: Record<string, SyncState["entries"][string]> = {
    ...syncState.entries,
  };

  for (const change of changes) {
    const module = change.module;
    if (!module) continue;

    const filePath = inferFilePath(change, projectDir);
    if (filePath === null) continue;

    const fileHash = hashContent(filePath);
    const existing = newEntries[module];

    newEntries[module] = {
      lastHash: fileHash,
      lastSyncedAt: now,
      mappedSpecs: existing?.mappedSpecs ?? [],
      mappedObsidianNodes: existing?.mappedObsidianNodes ?? [],
    };
  }

  saveSyncState(projectDir, { entries: newEntries });
}

/**
 * Detect conflicts between the impact report's affected specs and any
 * manually-edited content on disk.
 *
 * A spec is considered "manually edited" if it exists but does NOT contain
 * the `Auto-generated by sdd-exoskeleton` marker.
 */
export function detectConflicts(
  impact: ImpactReport,
  projectDir: string,
): ConflictReport {
  const conflicts: { spec: string; reason: string }[] = [];

  for (const spec of impact.affectedSpecs) {
    const specPath = path.join(
      projectDir,
      "openspec",
      "specs",
      "modules",
      spec,
    );
    const content = safeRead(specPath);

    if (content === null) continue;

    if (!content.includes(AUTO_GENERATED_MARKER)) {
      conflicts.push({
        spec,
        reason: `Spec "${spec}" contains manual edits (not auto-generated by sdd-exoskeleton)`,
      });
    }
  }

  return {
    hasConflict: conflicts.length > 0,
    conflicts,
  };
}
