import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

import {
  generateClaudeMd,
  generateAgentsMd,
  writeConstitution,
} from "../../src/generators/constitution.js";
import type { SddConfig } from "../../src/config.js";
import type { ModuleTopology } from "../../src/analyzers/structure.js";
import type { ModuleInfo } from "../../src/integrations/codegraph.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "sdd-constitution-test-"));
}

function readFile(fp: string): string {
  return fs.readFileSync(fp, "utf-8");
}

function fileExists(fp: string): boolean {
  try {
    return fs.statSync(fp).isFile();
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

function makeConfig(overrides?: Partial<SddConfig>): SddConfig {
  return {
    version: "0.1.0",
    project: {
      name: "my-project",
      languages: ["typescript"],
      rootDir: "/app",
      srcDir: "src",
    },
    codegraph: {
      indexPath: ".codegraph",
      mcpPort: 0,
    },
    openspec: {
      path: "openspec",
      changeDir: "openspec/changes",
    },
    obsidian: {
      vaultPath: "sdd-vault",
      strategy: "hybrid",
    },
    sync: {
      mode: "manual",
      lastSyncRef: "",
      lastSyncAt: "",
    },
    ...overrides,
  };
}

function makeSingleModule(overrides?: Partial<ModuleInfo>): ModuleInfo {
  return {
    name: "auth",
    path: "src/auth",
    files: ["src/auth/login.ts", "src/auth/logout.ts", "src/auth/session.ts"],
    exports: ["login", "logout", "validateSession"],
    ...overrides,
  };
}

function makeTopology(modules: ModuleInfo[]): ModuleTopology {
  return {
    modules,
    edges: [],
    entryPoints: [],
  };
}

function makeEmptyTopology(): ModuleTopology {
  return {
    modules: [],
    edges: [],
    entryPoints: [],
  };
}

// ---------------------------------------------------------------------------
// generateClaudeMd
// ---------------------------------------------------------------------------

describe("generateClaudeMd", () => {
  it("includes the auto-generation marker", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("Auto-generated by sdd-exoskeleton");
  });

  it("includes the project name", () => {
    const config = makeConfig({ project: { ...makeConfig().project, name: "my-app" } });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("# my-app");
  });

  it("includes the project overview with source directory and languages", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## Project Overview");
    expect(output).toContain("**Source:** `src`");
    expect(output).toContain("**Languages:** `typescript`");
  });

  it("includes tech stack section with language tooling", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: ["typescript", "python"] },
    });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## Tech Stack");
    expect(output).toContain("### Typescript");
    expect(output).toContain("eslint");
    expect(output).toContain("prettier");
    expect(output).toContain("### Python");
    expect(output).toContain("ruff");
    expect(output).toContain("black");
  });

  it("handles unknown language gracefully in tech stack", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: ["typescript", "elixir"] },
    });
    const topology = makeEmptyTopology();

    expect(() => generateClaudeMd(config, topology)).not.toThrow();
    const output = generateClaudeMd(config, topology);
    expect(output).toContain("_No tooling configuration available._");
  });

  it("includes module map with sorted modules", () => {
    const modules: ModuleInfo[] = [
      makeSingleModule({ name: "database", path: "src/database", files: ["src/database/connection.ts"], exports: ["connect", "query"] }),
      makeSingleModule(), // auth — uses default 3 files, 3 exports
      makeSingleModule({ name: "utils", path: "src/utils", files: ["src/utils/helpers.ts"], exports: ["formatDate"] }),
    ];
    const config = makeConfig();
    const topology = makeTopology(modules);

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## Module Map");
    // Modules should appear alphabetically
    const authIdx = output.indexOf("**auth**");
    const dbIdx = output.indexOf("**database**");
    const utilsIdx = output.indexOf("**utils**");
    expect(authIdx).toBeLessThan(dbIdx);
    expect(dbIdx).toBeLessThan(utilsIdx);

    // Verify file and export counts
    expect(output).toContain("(3 files, 3 exports)"); // auth has 3 files, 3 exports
    expect(output).toContain("(1 files, 2 exports)"); // database has 1 file, 2 exports
    expect(output).toContain("(1 files, 1 exports)"); // utils has 1 file, 1 export
  });

  it("shows placeholder when no modules", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("_No modules indexed yet._");
  });

  it("includes coding standards section", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: ["typescript", "go"] },
    });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## Coding Standards");
    expect(output).toContain("typescript/coding-style.md");
    expect(output).toContain("go/coding-style.md");
  });

  it("includes SDD workflow section", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## SDD Workflow");
    expect(output).toContain("Specification-Driven Development (SDD)");
  });

  it("includes SDD commands", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("`sdd status`");
    expect(output).toContain("`sdd sync`");
    expect(output).toContain("`sdd doctor`");
  });

  it("includes openspec paths from config", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("openspec/specs/");
    expect(output).toContain("openspec/changes");
  });

  it("includes obsidian vault path from config", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("sdd-vault");
  });

  it("includes SDD workflow steps", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("Propose changes");
    expect(output).toContain("Implement after spec approval");
    expect(output).toContain("Archive completed changes");
  });

  it("does not mutate the config object", () => {
    const config = makeConfig();
    const originalName = config.project.name;
    const topology = makeTopology([makeSingleModule()]);

    generateClaudeMd(config, topology);

    expect(config.project.name).toBe(originalName);
  });

  it("does not mutate the topology object", () => {
    const config = makeConfig();
    const modules: ModuleInfo[] = [makeSingleModule()];
    const topology = makeTopology(modules);
    const originalModuleCount = topology.modules.length;

    generateClaudeMd(config, topology);

    expect(topology.modules.length).toBe(originalModuleCount);
  });

  it("includes all 5 major sections", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("## Project Overview");
    expect(output).toContain("## Tech Stack");
    expect(output).toContain("## Module Map");
    expect(output).toContain("## Coding Standards");
    expect(output).toContain("## SDD Workflow");
  });
});

// ---------------------------------------------------------------------------
// generateAgentsMd
// ---------------------------------------------------------------------------

describe("generateAgentsMd", () => {
  it("includes the auto-generation marker", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("Auto-generated by sdd-exoskeleton");
  });

  it("includes the project name in title", () => {
    const config = makeConfig({ project: { ...makeConfig().project, name: "super-app" } });
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("# super-app — AI Agent Instructions");
  });

  it("includes project context with languages and source dir", () => {
    const config = makeConfig({
      project: {
        ...makeConfig().project,
        languages: ["typescript", "python"],
        srcDir: "lib",
      },
    });
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("## Project Context");
    expect(output).toContain("`typescript`, `python`");
    expect(output).toContain("`lib`");
  });

  it("includes module structure with sorted modules", () => {
    const modules: ModuleInfo[] = [
      makeSingleModule({ name: "utils", path: "src/utils", files: [], exports: [] }),
      makeSingleModule({ name: "auth", path: "src/auth", files: [], exports: [] }),
    ];
    const config = makeConfig();
    const topology = makeTopology(modules);

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("## Module Structure");
    const authIdx = output.indexOf("**auth**");
    const utilsIdx = output.indexOf("**utils**");
    expect(authIdx).toBeLessThan(utilsIdx);
  });

  it("shows placeholder when no modules", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("_No modules indexed yet._");
  });

  it("includes SDD commands section", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("## SDD Commands");
    expect(output).toContain("`sdd status`");
    expect(output).toContain("`sdd sync`");
    expect(output).toContain("`sdd doctor`");
  });

  it("includes coding rules with linter and formatter per language", () => {
    const config = makeConfig({
      project: {
        ...makeConfig().project,
        languages: ["typescript", "rust"],
      },
    });
    const topology = makeEmptyTopology();

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("## Coding Rules");
    expect(output).toContain("eslint");
    expect(output).toContain("prettier");
    expect(output).toContain("clippy");
    expect(output).toContain("rustfmt");
  });

  it("handles unknown language in coding rules", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: ["typescript", "haskell"] },
    });
    const topology = makeEmptyTopology();

    expect(() => generateAgentsMd(config, topology)).not.toThrow();
    const output = generateAgentsMd(config, topology);
    expect(output).toContain("_no tooling configured_");
  });

  it("does not mutate the config object", () => {
    const config = makeConfig();
    const originalName = config.project.name;
    const topology = makeTopology([makeSingleModule()]);

    generateAgentsMd(config, topology);

    expect(config.project.name).toBe(originalName);
  });

  it("does not mutate the topology object", () => {
    const config = makeConfig();
    const modules: ModuleInfo[] = [makeSingleModule()];
    const topology = makeTopology(modules);
    const originalCount = topology.modules.length;

    generateAgentsMd(config, topology);

    expect(topology.modules.length).toBe(originalCount);
  });

  it("includes all 4 major sections", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    const output = generateAgentsMd(config, topology);

    expect(output).toContain("## Project Context");
    expect(output).toContain("## Module Structure");
    expect(output).toContain("## SDD Commands");
    expect(output).toContain("## Coding Rules");
  });
});

// ---------------------------------------------------------------------------
// writeConstitution
// ---------------------------------------------------------------------------

describe("writeConstitution", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = createTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("writes both CLAUDE.md and AGENTS.md to the project directory", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const result = writeConstitution(tmpDir, config, topology);

    expect(fileExists(path.join(tmpDir, "CLAUDE.md"))).toBe(true);
    expect(fileExists(path.join(tmpDir, "AGENTS.md"))).toBe(true);
    expect(result.written).toContain(path.join(tmpDir, "CLAUDE.md"));
    expect(result.written).toContain(path.join(tmpDir, "AGENTS.md"));
    expect(result.skipped).toEqual([]);
  });

  it("returns correct result with written and skipped lists", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    const result = writeConstitution(tmpDir, config, topology);

    expect(result.written).toHaveLength(2);
    expect(result.skipped).toHaveLength(0);
  });

  it("overwrites existing files that contain the auto-generation marker", () => {
    const originalContent = `# Old Content\n\n> Auto-generated by sdd-exoskeleton\n\nOld content here.`;
    fs.writeFileSync(path.join(tmpDir, "CLAUDE.md"), originalContent, "utf-8");

    const config = makeConfig();
    const topology = makeEmptyTopology();

    writeConstitution(tmpDir, config, topology);

    const newContent = readFile(path.join(tmpDir, "CLAUDE.md"));
    expect(newContent).not.toBe(originalContent);
    expect(newContent).toContain("## Project Overview");
  });

  it("skips existing files that do NOT contain the auto-generation marker", () => {
    const userContent = "# My Custom CLAUDE.md\n\nHand-written content.";
    fs.writeFileSync(path.join(tmpDir, "CLAUDE.md"), userContent, "utf-8");

    const config = makeConfig();
    const topology = makeEmptyTopology();

    const result = writeConstitution(tmpDir, config, topology);

    // CLAUDE.md should NOT be overwritten
    expect(readFile(path.join(tmpDir, "CLAUDE.md"))).toBe(userContent);
    // AGENTS.md should still be written
    expect(fileExists(path.join(tmpDir, "AGENTS.md"))).toBe(true);

    expect(result.skipped).toContain(path.join(tmpDir, "CLAUDE.md"));
    expect(result.written).toContain(path.join(tmpDir, "AGENTS.md"));
  });

  it("skips AGENTS.md when it exists without marker", () => {
    const userContent = "# My Custom AGENTS.md\n\nHand-written.";
    fs.writeFileSync(path.join(tmpDir, "AGENTS.md"), userContent, "utf-8");

    const config = makeConfig();
    const topology = makeEmptyTopology();

    const result = writeConstitution(tmpDir, config, topology);

    expect(readFile(path.join(tmpDir, "AGENTS.md"))).toBe(userContent);
    expect(result.skipped).toContain(path.join(tmpDir, "AGENTS.md"));
    expect(result.written).toContain(path.join(tmpDir, "CLAUDE.md"));
  });

  it("skips both files when both exist without marker", () => {
    const claudeContent = "# Custom CLAUDE.md\n\nCustom.";
    const agentsContent = "# Custom AGENTS.md\n\nCustom.";
    fs.writeFileSync(path.join(tmpDir, "CLAUDE.md"), claudeContent, "utf-8");
    fs.writeFileSync(path.join(tmpDir, "AGENTS.md"), agentsContent, "utf-8");

    const config = makeConfig();
    const topology = makeEmptyTopology();

    const result = writeConstitution(tmpDir, config, topology);

    expect(readFile(path.join(tmpDir, "CLAUDE.md"))).toBe(claudeContent);
    expect(readFile(path.join(tmpDir, "AGENTS.md"))).toBe(agentsContent);
    expect(result.written).toEqual([]);
    expect(result.skipped).toHaveLength(2);
  });

  it("writes with module data when modules are provided", () => {
    const config = makeConfig();
    const modules: ModuleInfo[] = [
      makeSingleModule(),
      makeSingleModule({ name: "utils", path: "src/utils", files: ["src/utils/helpers.ts"], exports: ["formatDate"] }),
    ];
    const topology = makeTopology(modules);

    writeConstitution(tmpDir, config, topology);

    const claudeContent = readFile(path.join(tmpDir, "CLAUDE.md"));
    expect(claudeContent).toContain("**auth**");
    expect(claudeContent).toContain("**utils**");
  });

  it("writes with multiple languages in tech stack", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: ["typescript", "go", "rust"] },
    });
    const topology = makeEmptyTopology();

    writeConstitution(tmpDir, config, topology);

    const claudeContent = readFile(path.join(tmpDir, "CLAUDE.md"));
    expect(claudeContent).toContain("### Typescript");
    expect(claudeContent).toContain("### Go");
    expect(claudeContent).toContain("### Rust");
  });

  it("handles empty modules gracefully", () => {
    const config = makeConfig();
    const topology = makeEmptyTopology();

    expect(() => writeConstitution(tmpDir, config, topology)).not.toThrow();
    expect(fileExists(path.join(tmpDir, "CLAUDE.md"))).toBe(true);
  });

  it("does not mutate config or topology during write", () => {
    const config = makeConfig();
    const modules: ModuleInfo[] = [makeSingleModule()];
    const topology = makeTopology(modules);
    const originalName = config.project.name;
    const originalModuleCount = topology.modules.length;

    writeConstitution(tmpDir, config, topology);

    expect(config.project.name).toBe(originalName);
    expect(topology.modules.length).toBe(originalModuleCount);
  });

  it("CLAUDE.md contains all expected top-level sections", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    writeConstitution(tmpDir, config, topology);

    const content = readFile(path.join(tmpDir, "CLAUDE.md"));
    expect(content).toContain("## Project Overview");
    expect(content).toContain("## Tech Stack");
    expect(content).toContain("## Module Map");
    expect(content).toContain("## Coding Standards");
    expect(content).toContain("## SDD Workflow");
  });

  it("AGENTS.md contains all expected top-level sections", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    writeConstitution(tmpDir, config, topology);

    const content = readFile(path.join(tmpDir, "AGENTS.md"));
    expect(content).toContain("## Project Context");
    expect(content).toContain("## Module Structure");
    expect(content).toContain("## SDD Commands");
    expect(content).toContain("## Coding Rules");
  });
});

// ---------------------------------------------------------------------------
// Edge cases
// ---------------------------------------------------------------------------

describe("constitution edge cases", () => {
  it("handles project names with special markdown characters", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, name: "my *awesome* _project_" },
    });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    // Names should be escaped
    expect(output).toContain("# my \\*awesome\\* \\_project\\_");
  });

  it("handles project names with backticks", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, name: "`evil` project" },
    });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    expect(output).toContain("\\`evil\\` project");
  });

  it("handles empty language list gracefully", () => {
    const config = makeConfig({
      project: { ...makeConfig().project, languages: [] },
    });
    const topology = makeEmptyTopology();

    const output = generateClaudeMd(config, topology);

    // Should not crash, just have empty tech stack / coding standards
    expect(output).toContain("## Tech Stack");
    expect(output).toContain("## Coding Standards");
  });

  it("handles project with many modules (stress test)", () => {
    const modules: ModuleInfo[] = [];
    for (let i = 0; i < 100; i++) {
      modules.push({
        name: `module-${i}`,
        path: `src/module-${i}`,
        files: [`src/module-${i}/index.ts`],
        exports: [`export${i}`],
      });
    }
    const config = makeConfig();
    const topology = makeTopology(modules);

    expect(() => generateClaudeMd(config, topology)).not.toThrow();
    expect(() => generateAgentsMd(config, topology)).not.toThrow();

    const claudeOutput = generateClaudeMd(config, topology);
    // First module should appear (sorted: module-0)
    expect(claudeOutput).toContain("**module-0**");
    // Last by name (module-99)
    expect(claudeOutput).toContain("**module-99**");
  });

  it("generates idempotent output (calling twice gives same result)", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    const first = generateClaudeMd(config, topology);
    const second = generateClaudeMd(config, topology);

    expect(first).toBe(second);
  });

  it("AGENTS.md has simpler structure than CLAUDE.md", () => {
    const config = makeConfig();
    const topology = makeTopology([makeSingleModule()]);

    const claudeContent = generateClaudeMd(config, topology);
    const agentsContent = generateAgentsMd(config, topology);

    // AGENTS.md should be shorter than CLAUDE.md
    expect(agentsContent.length).toBeLessThan(claudeContent.length);
    // AGENTS.md should not contain workflow steps
    expect(agentsContent).not.toContain("Propose changes");
  });
});
