import { describe, test, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import * as child_process from "node:child_process";

import { runSync } from "../../src/commands/sync.js";
import type { SyncOptions, SyncResult } from "../../src/commands/sync.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createTempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "sdd-sync-test-"));
}

function cleanupDir(dir: string): void {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function initGitRepo(dir: string): void {
  child_process.execSync("git init", { cwd: dir, stdio: "pipe" });
  child_process.execSync("git config user.email test@example.com", {
    cwd: dir,
    stdio: "pipe",
  });
  child_process.execSync('git config user.name "Test User"', {
    cwd: dir,
    stdio: "pipe",
  });
}

function commitFile(
  dir: string,
  fileName: string,
  content: string,
  message?: string,
): void {
  const fullPath = path.join(dir, fileName);
  const dirName = path.dirname(fullPath);
  fs.mkdirSync(dirName, { recursive: true });
  fs.writeFileSync(fullPath, content, "utf-8");
  child_process.execSync(`git add "${fileName}"`, {
    cwd: dir,
    stdio: "pipe",
  });
  child_process.execSync(
    `git commit -m "${message ?? "add " + fileName}"`,
    { cwd: dir, stdio: "pipe" },
  );
}

function modifyFile(
  dir: string,
  fileName: string,
  newContent: string,
  message?: string,
): void {
  const fullPath = path.join(dir, fileName);
  fs.writeFileSync(fullPath, newContent, "utf-8");
  child_process.execSync(`git add "${fileName}"`, {
    cwd: dir,
    stdio: "pipe",
  });
  child_process.execSync(
    `git commit -m "${message ?? "modify " + fileName}"`,
    { cwd: dir, stdio: "pipe" },
  );
}

function removeFile(dir: string, fileName: string, message?: string): void {
  fs.rmSync(path.join(dir, fileName));
  child_process.execSync(`git add "${fileName}"`, {
    cwd: dir,
    stdio: "pipe",
  });
  child_process.execSync(
    `git commit -m "${message ?? "remove " + fileName}"`,
    { cwd: dir, stdio: "pipe" },
  );
}

function getHeadSha(dir: string): string {
  return child_process
    .execSync("git rev-parse HEAD", { cwd: dir, encoding: "utf-8" })
    .trim();
}

interface ConfigOverrides {
  sync?: {
    mode?: string;
    lastSyncRef?: string;
    lastSyncAt?: string;
  };
}

function writeConfig(dir: string, overrides: ConfigOverrides = {}): void {
  const sddDir = path.join(dir, ".sdd-exoskeleton");
  fs.mkdirSync(sddDir, { recursive: true });

  const config = {
    version: "0.1.0",
    project: {
      name: "test-project",
      languages: ["typescript"],
      rootDir: dir,
      srcDir: "src",
    },
    codegraph: {
      indexPath: ".codegraph",
      mcpPort: 0,
    },
    openspec: {
      path: "openspec",
      changeDir: "openspec/changes",
    },
    obsidian: {
      vaultPath: "sdd-vault",
      strategy: "hybrid" as const,
    },
    sync: {
      mode: "manual" as const,
      lastSyncRef: "",
      lastSyncAt: "",
      ...overrides.sync,
    },
  };

  fs.writeFileSync(
    path.join(sddDir, "config.json"),
    JSON.stringify(config, null, 2),
  );
}

function writeSpecFile(
  dir: string,
  specName: string,
  content: string,
): void {
  const specDir = path.join(dir, "openspec", "specs", "modules");
  fs.mkdirSync(specDir, { recursive: true });
  fs.writeFileSync(path.join(specDir, specName), content, "utf-8");
}

const AUTO_GENERATED_MARKER = "Auto-generated by sdd-exoskeleton";

// ---------------------------------------------------------------------------
// process.exit mocks for error-case tests
// ---------------------------------------------------------------------------

/**
 * Spy on process.exit so tests asserting error exits don't kill the test runner.
 * The mock throws so `runSync` rejects, which tests can catch.
 */
function mockProcessExit(): ReturnType<typeof vi.spyOn> {
  return vi.spyOn(process, "exit").mockImplementation(((_code) => {
    throw new Error("process.exit");
  }) as never);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("runSync", () => {
  describe("error exits", () => {
    test("errors when not a git repo", async () => {
      const exitSpy = mockProcessExit();
      const tmpDir = createTempDir();

      try {
        await expect(runSync(tmpDir, {})).rejects.toThrow("process.exit");
      } finally {
        exitSpy.mockRestore();
        cleanupDir(tmpDir);
      }
    });

    test("errors when no --since and config has no lastSyncRef", async () => {
      const exitSpy = mockProcessExit();
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: "", lastSyncAt: "" } });

      try {
        await expect(runSync(tmpDir, {})).rejects.toThrow("process.exit");
      } finally {
        exitSpy.mockRestore();
        cleanupDir(tmpDir);
      }
    });
  });

  describe("no changes", () => {
    test("returns empty result when nothing changed", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);
      commitFile(tmpDir, "src/index.ts", "export const x = 1;", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      const result = await runSync(tmpDir, { since });

      expect(result.changedFiles).toBe(0);
      expect(result.changedSymbols).toBe(0);
      expect(result.impactLevel).toBe("low");
      expect(result.conflictReport.hasConflict).toBe(false);

      cleanupDir(tmpDir);
    });
  });

  describe("basic sync flow", () => {
    test("runs full pipeline end-to-end with real git repo", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      // Initial commit to set baseline
      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Write spec file with auto-generated marker (no conflicts)
      writeSpecFile(
        tmpDir,
        "auth.md",
        `# Auth Spec\n\n> ${AUTO_GENERATED_MARKER}\n\n## Authentication\n`,
      );

      // Make a change
      modifyFile(
        tmpDir,
        "src/auth/login.ts",
        "export function login(token: string) {}",
        "add token param",
      );

      const result = await runSync(tmpDir, { since });

      // Verify result shape
      expect(result.changedFiles).toBeGreaterThan(0);
      expect(result.changedSymbols).toBeGreaterThan(0);
      expect(["low", "medium", "high"]).toContain(result.impactLevel);
      expect(result.conflictReport.hasConflict).toBe(false);
      expect(result.dryRun).toBe(false);
      expect(result.deltaPath).toBeDefined();
      expect(result.deltaPath).toContain("openspec");

      // Verify delta was created on disk
      if (result.deltaPath) {
        expect(fs.existsSync(result.deltaPath)).toBe(true);
        const proposalPath = path.join(result.deltaPath, "proposal.md");
        expect(fs.existsSync(proposalPath)).toBe(true);
      }

      // Verify sync state was updated
      const statePath = path.join(tmpDir, ".sdd-exoskeleton", "sync-state.json");
      expect(fs.existsSync(statePath)).toBe(true);
      const state = JSON.parse(fs.readFileSync(statePath, "utf-8"));
      const entries = state.entries ?? {};
      expect(Object.keys(entries).length).toBeGreaterThan(0);

      // Verify config was updated
      const configPath = path.join(tmpDir, ".sdd-exoskeleton", "config.json");
      const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      expect(config.sync.lastSyncRef).toBeTruthy();
      expect(config.sync.lastSyncAt).toBeTruthy();

      cleanupDir(tmpDir);
    });

    test("syncs multiple changed files across modules", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      commitFile(tmpDir, "src/services/payment.ts", "export function pay() {}", "add payment");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Modify both files
      modifyFile(tmpDir, "src/auth/login.ts", "export function login(x: string) {}", "mod login");
      modifyFile(tmpDir, "src/services/payment.ts", "export function pay(amt: number) {}", "mod pay");

      const result = await runSync(tmpDir, { since });

      expect(result.changedFiles).toBe(2);
      expect(result.changedSymbols).toBe(2);
      expect(result.dryRun).toBe(false);

      cleanupDir(tmpDir);
    });

    test("handles file additions and removals", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/index.ts", "export const base = 1;", "initial");
      commitFile(tmpDir, "src/to-remove.ts", "export const old = 'x';", "add old");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Add a new file and remove another
      commitFile(tmpDir, "src/new-file.ts", "export const fresh = 2;", "add new");
      removeFile(tmpDir, "src/to-remove.ts", "remove old");

      const result = await runSync(tmpDir, { since });

      expect(result.changedFiles).toBe(2);

      cleanupDir(tmpDir);
    });
  });

  describe("--dry-run", () => {
    test("reports changes but does not write delta or update state", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      modifyFile(
        tmpDir,
        "src/auth/login.ts",
        "export function login(token: string) {}",
        "add param",
      );

      // Record state before run
      const stateBefore = fs.existsSync(
        path.join(tmpDir, ".sdd-exoskeleton", "sync-state.json"),
      );
      const configBefore = JSON.parse(
        fs.readFileSync(path.join(tmpDir, ".sdd-exoskeleton", "config.json"), "utf-8"),
      );

      const result = await runSync(tmpDir, { since, dryRun: true });

      // Result must be marked as dry run
      expect(result.dryRun).toBe(true);
      expect(result.changedFiles).toBeGreaterThan(0);
      expect(result.deltaPath).toBeUndefined();

      // No delta folder should exist
      const changesDir = path.join(tmpDir, "openspec", "changes");
      const changeEntries = fs.existsSync(changesDir)
        ? fs.readdirSync(changesDir)
        : [];
      // Any existing change dirs with "-sync" suffix should NOT have been created by this run
      // The function generates a timestamp-based folder; just check there are no new sync folders
      const syncFolders = changeEntries.filter((e) => e.endsWith("-sync"));
      expect(syncFolders.length).toBe(0);

      // Config should be unchanged (lastSyncRef not updated)
      const configAfter = JSON.parse(
        fs.readFileSync(path.join(tmpDir, ".sdd-exoskeleton", "config.json"), "utf-8"),
      );
      expect(configAfter.sync.lastSyncRef).toBe(configBefore.sync.lastSyncRef);

      cleanupDir(tmpDir);
    });
  });

  describe("conflict detection", () => {
    test("detects manual-edited specs and returns conflict report without --resolve", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Write spec that references "auth" but does NOT have the auto-generated marker
      writeSpecFile(
        tmpDir,
        "auth-spec.md",
        "# Authentication Module\n\nThis is a manually edited spec about authentication.\n",
      );

      modifyFile(
        tmpDir,
        "src/auth/login.ts",
        "export function login(token: string) {}",
        "add param",
      );

      const result = await runSync(tmpDir, { since });

      // Should detect the conflict
      expect(result.conflictReport.hasConflict).toBe(true);
      expect(result.conflictReport.conflicts.length).toBeGreaterThan(0);
      expect(result.conflictReport.conflicts[0].spec).toBe("auth-spec.md");
      expect(result.conflictReport.conflicts[0].reason).toContain("manual");

      // Should NOT have written delta (returned early due to conflict)
      expect(result.deltaPath).toBeUndefined();
      expect(result.dryRun).toBe(false);

      cleanupDir(tmpDir);
    });

    test("continues past conflicts when --resolve strategy is provided", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      writeSpecFile(
        tmpDir,
        "auth-spec.md",
        "# Auth\n\nManual content about auth module.\n",
      );

      modifyFile(
        tmpDir,
        "src/auth/login.ts",
        "export function login(token: string) {}",
        "add param",
      );

      const result = await runSync(tmpDir, {
        since,
        resolve: "code-first",
      });

      // Conflict should be detected but we proceed anyway
      expect(result.conflictReport.hasConflict).toBe(true);
      // With resolve strategy, delta should be generated
      expect(result.deltaPath).toBeDefined();
      expect(result.dryRun).toBe(false);

      cleanupDir(tmpDir);
    });

    test("no conflict when specs have auto-generated marker", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/utils/format.ts", "export function format() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Spec with auto-generated marker → no conflict
      writeSpecFile(
        tmpDir,
        "utils.md",
        `# Utils\n\n> ${AUTO_GENERATED_MARKER}\n\nUtility functions for the utils module.\n`,
      );

      modifyFile(
        tmpDir,
        "src/utils/format.ts",
        "export function format(x: string) {}",
        "add param",
      );

      const result = await runSync(tmpDir, { since });

      expect(result.conflictReport.hasConflict).toBe(false);

      cleanupDir(tmpDir);
    });
  });

  describe("--files filtering", () => {
    test("only processes files matching the filter pattern", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      commitFile(tmpDir, "src/services/payment.ts", "export function pay() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Modify both files
      modifyFile(tmpDir, "src/auth/login.ts", "export function login(x: string) {}", "mod login");
      modifyFile(tmpDir, "src/services/payment.ts", "export function pay(amt: number) {}", "mod pay");

      // Only sync auth files
      const result = await runSync(tmpDir, { since, files: "src/auth" });

      // Should only have processed the auth file
      expect(result.changedSymbols).toBe(1);

      cleanupDir(tmpDir);
    });

    test("multiple comma-separated patterns", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      commitFile(tmpDir, "src/services/payment.ts", "export function pay() {}", "initial");
      commitFile(tmpDir, "src/utils/format.ts", "export function format() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      modifyFile(tmpDir, "src/auth/login.ts", "export function login(x: string) {}", "mod login");
      modifyFile(tmpDir, "src/services/payment.ts", "export function pay(a: number) {}", "mod pay");
      modifyFile(tmpDir, "src/utils/format.ts", "export function format(v: string) {}", "mod fmt");

      // Select two of three
      const result = await runSync(tmpDir, {
        since,
        files: "src/auth,src/utils",
      });

      expect(result.changedSymbols).toBe(2);

      cleanupDir(tmpDir);
    });

    test("returns nothing to sync when filter matches no changes", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      modifyFile(tmpDir, "src/auth/login.ts", "export function login(x: string) {}", "mod");

      const result = await runSync(tmpDir, { since, files: "src/nonexistent" });

      expect(result.changedFiles).toBe(0);
      expect(result.changedSymbols).toBe(0);

      cleanupDir(tmpDir);
    });
  });

  describe("SyncResult shape", () => {
    test("result has all expected keys with correct types", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      modifyFile(
        tmpDir,
        "src/auth/login.ts",
        "export function login(token: string) {}",
        "add param",
      );

      const result = await runSync(tmpDir, { since });

      expect(typeof result.changedFiles).toBe("number");
      expect(typeof result.changedSymbols).toBe("number");
      expect(["low", "medium", "high"]).toContain(result.impactLevel);
      expect(result.conflictReport).toHaveProperty("hasConflict");
      expect(result.conflictReport).toHaveProperty("conflicts");
      expect(Array.isArray(result.conflictReport.conflicts)).toBe(true);
      expect(typeof result.dryRun).toBe("boolean");

      if (result.deltaPath) {
        expect(typeof result.deltaPath).toBe("string");
      }

      cleanupDir(tmpDir);
    });
  });

  describe("handles rename detection", () => {
    test("detects renamed files", async () => {
      const tmpDir = createTempDir();
      initGitRepo(tmpDir);

      commitFile(tmpDir, "src/auth/old-login.ts", "export function login() {}", "initial");
      const since = getHeadSha(tmpDir);
      writeConfig(tmpDir, { sync: { lastSyncRef: since, lastSyncAt: new Date().toISOString() } });

      // Rename via git mv
      child_process.execSync("git mv src/auth/old-login.ts src/auth/new-login.ts", {
        cwd: tmpDir,
        stdio: "pipe",
      });
      child_process.execSync('git commit -m "rename login file"', {
        cwd: tmpDir,
        stdio: "pipe",
      });

      const result = await runSync(tmpDir, { since });

      // Renames are detected by git as remove+add by the diff command
      // detectChanges would see the old file as removed and new as added
      // Both are valid changes to sync
      expect(result.changedFiles).toBeGreaterThan(0);

      cleanupDir(tmpDir);
    });
  });
});
