import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import {
  generateDelta,
  updateSyncState,
  detectConflicts,
} from "../../src/sync/delta.js";
import type { ImpactReport } from "../../src/sync/impact.js";
import type { SymbolChange } from "../../src/sync/detector.js";
import { loadSyncState, saveSyncState } from "../../src/sync-state.js";
import { safeRead } from "../../src/utils/fs.js";

function createSymbol(
  overrides: Partial<SymbolChange> = {},
): SymbolChange {
  return {
    name: "TestSymbol",
    type: "modified",
    module: "testModule",
    summary: "modified file src/testModule/test.ts",
    affectedApis: [],
    affectedModules: [],
    ...overrides,
  };
}

function createImpactReport(
  overrides: Partial<ImpactReport> = {},
): ImpactReport {
  return {
    changes: [],
    affectedSpecs: [],
    affectedModules: [],
    summary: "No changes detected.",
    impactLevel: "low",
    ...overrides,
  };
}

describe("generateDelta", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "sdd-delta-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("creates a change folder with proposal.md and correct content", () => {
    const impact = createImpactReport({
      changes: [
        createSymbol({
          name: "Login",
          type: "added",
          module: "auth",
          summary: "added file src/auth/login.ts",
        }),
      ],
      affectedModules: ["auth"],
      affectedSpecs: ["auth-spec.md"],
      summary: "Low impact: 1 symbol change(s) across 1 module(s).",
      impactLevel: "low",
    });

    const changeDir = generateDelta(impact, tmpDir);

    expect(fs.existsSync(changeDir)).toBe(true);
    expect(changeDir).toContain(
      path.join(tmpDir, "openspec", "changes"),
    );

    const proposalPath = path.join(changeDir, "proposal.md");
    expect(fs.existsSync(proposalPath)).toBe(true);

    const content = safeRead(proposalPath);
    expect(content).not.toBeNull();
    expect(content!).toContain("# Sync Change:");
    expect(content!).toContain(
      "> Auto-generated by sdd-exoskeleton",
    );
    expect(content!).toContain(
      "Low impact: 1 symbol change(s) across 1 module(s).",
    );
    expect(content!).toContain("## Impact Level: low");
    expect(content!).toContain("- auth");
    expect(content!).toContain("- auth-spec.md");
    expect(content!).toContain(
      "- **Login** (added): added file src/auth/login.ts",
    );
  });

  it("handles empty changes gracefully", () => {
    const impact = createImpactReport();

    const changeDir = generateDelta(impact, tmpDir);
    const proposalPath = path.join(changeDir, "proposal.md");
    const content = safeRead(proposalPath);

    expect(content).not.toBeNull();
    expect(content!).toContain("No changes detected.");
    expect(content!).toContain("- (none)");
  });

  it("creates folder structure under openspec/changes/ with -sync suffix", () => {
    const impact = createImpactReport();

    const changeDir = generateDelta(impact, tmpDir);

    const relative = path.relative(tmpDir, changeDir);
    const parts = relative.split(path.sep);
    expect(parts[0]).toBe("openspec");
    expect(parts[1]).toBe("changes");
    expect(parts[2]).toMatch(/-sync$/);
  });

  it("handles multiple changes correctly", () => {
    const impact = createImpactReport({
      changes: [
        createSymbol({
          name: "Login",
          type: "added",
          module: "auth",
          summary: "added file src/auth/login.ts",
        }),
        createSymbol({
          name: "Logout",
          type: "removed",
          module: "auth",
          summary: "removed file src/auth/logout.ts",
        }),
      ],
      affectedModules: ["auth"],
      summary:
        "Low impact: 2 symbol change(s) across 1 module(s).",
    });

    const changeDir = generateDelta(impact, tmpDir);
    const content = safeRead(path.join(changeDir, "proposal.md"));

    expect(content).toContain(
      "- **Login** (added): added file src/auth/login.ts",
    );
    expect(content).toContain(
      "- **Logout** (removed): removed file src/auth/logout.ts",
    );
  });

  it("handles high-impact reports with multiple affected modules", () => {
    const impact = createImpactReport({
      changes: [
        createSymbol({
          name: "UserService",
          type: "modified",
          module: "auth",
          summary: "modified file src/auth/user-service.ts",
        }),
      ],
      affectedModules: ["auth", "utils", "dashboard"],
      affectedSpecs: ["auth-spec.md", "dashboard-spec.md"],
      summary:
        "High impact: 1 symbol change(s) across 3 module(s). 2 spec(s) potentially affected.",
      impactLevel: "high",
    });

    const changeDir = generateDelta(impact, tmpDir);
    const content = safeRead(path.join(changeDir, "proposal.md"));

    expect(content).toContain("## Impact Level: high");
    expect(content).toContain("- auth");
    expect(content).toContain("- utils");
    expect(content).toContain("- dashboard");
    expect(content).toContain("- auth-spec.md");
    expect(content).toContain("- dashboard-spec.md");
  });
});

describe("updateSyncState", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "sdd-delta-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("writes new hashes to sync-state.json for changed modules", () => {
    const srcDir = path.join(tmpDir, "src", "auth");
    fs.mkdirSync(srcDir, { recursive: true });
    fs.writeFileSync(
      path.join(srcDir, "login.ts"),
      "export const login = () => {};",
      "utf-8",
    );

    const changes: SymbolChange[] = [
      createSymbol({
        name: "Login",
        type: "modified",
        module: "auth",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries.auth).toBeDefined();
    expect(state.entries.auth.lastHash).toMatch(/^[a-f0-9]{64}$/);
    expect(state.entries.auth.lastSyncedAt).toBeDefined();
  });

  it("preserves existing mappedSpecs and mappedObsidianNodes when updating", () => {
    const srcDir = path.join(tmpDir, "src", "auth");
    fs.mkdirSync(srcDir, { recursive: true });
    fs.writeFileSync(
      path.join(srcDir, "login.ts"),
      "export const login = () => {};",
      "utf-8",
    );

    saveSyncState(tmpDir, {
      entries: {
        auth: {
          lastHash: "oldhash",
          lastSyncedAt: "2024-01-01T00:00:00.000Z",
          mappedSpecs: ["auth-spec.md"],
          mappedObsidianNodes: ["node-1"],
        },
      },
    });

    const changes: SymbolChange[] = [
      createSymbol({
        name: "Login",
        type: "modified",
        module: "auth",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries.auth.mappedSpecs).toEqual(["auth-spec.md"]);
    expect(state.entries.auth.mappedObsidianNodes).toEqual(["node-1"]);
    expect(state.entries.auth.lastHash).not.toBe("oldhash");
  });

  it("handles kebab-case filenames via symbol name matching", () => {
    const srcDir = path.join(tmpDir, "src", "components");
    fs.mkdirSync(srcDir, { recursive: true });
    fs.writeFileSync(
      path.join(srcDir, "user-profile.ts"),
      "export const UserProfile = () => {};",
      "utf-8",
    );

    const changes: SymbolChange[] = [
      createSymbol({
        name: "UserProfile",
        type: "modified",
        module: "components",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries.components).toBeDefined();
    expect(state.entries.components.lastHash).toMatch(/^[a-f0-9]{64}$/);
  });

  it("skips changes with empty module name", () => {
    const changes: SymbolChange[] = [
      createSymbol({
        name: "RootSymbol",
        type: "modified",
        module: "",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries).toEqual({});
  });

  it("skips changes when source file cannot be found", () => {
    const changes: SymbolChange[] = [
      createSymbol({
        name: "NonExistent",
        type: "modified",
        module: "phantom",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries.phantom).toBeUndefined();
  });

  it("does not mutate the input changes array", () => {
    const srcDir = path.join(tmpDir, "src", "auth");
    fs.mkdirSync(srcDir, { recursive: true });
    fs.writeFileSync(
      path.join(srcDir, "login.ts"),
      "export const login = () => {};",
      "utf-8",
    );

    const changes: SymbolChange[] = [
      createSymbol({
        name: "Login",
        type: "modified",
        module: "auth",
      }),
    ];
    const original = structuredClone(changes);

    updateSyncState(tmpDir, changes, "HEAD");

    expect(changes).toEqual(original);
  });

  it("updates multiple modules from multiple changes", () => {
    const authDir = path.join(tmpDir, "src", "auth");
    const utilsDir = path.join(tmpDir, "src", "utils");
    fs.mkdirSync(authDir, { recursive: true });
    fs.mkdirSync(utilsDir, { recursive: true });
    fs.writeFileSync(
      path.join(authDir, "login.ts"),
      "auth content",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(utilsDir, "format.ts"),
      "utils content",
      "utf-8",
    );

    const changes: SymbolChange[] = [
      createSymbol({
        name: "Login",
        type: "modified",
        module: "auth",
      }),
      createSymbol({
        name: "Format",
        type: "modified",
        module: "utils",
      }),
    ];

    updateSyncState(tmpDir, changes, "HEAD");

    const state = loadSyncState(tmpDir);
    expect(state.entries.auth).toBeDefined();
    expect(state.entries.utils).toBeDefined();
    expect(state.entries.auth.lastHash).not.toBe(
      state.entries.utils.lastHash,
    );
  });
});

describe("detectConflicts", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "sdd-delta-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("returns no conflicts for auto-generated specs", () => {
    const modulesDir = path.join(
      tmpDir,
      "openspec",
      "specs",
      "modules",
    );
    fs.mkdirSync(modulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(modulesDir, "auth-spec.md"),
      "# Auth Spec\n\nAuto-generated by sdd-exoskeleton\n\nSome content.",
      "utf-8",
    );

    const impact = createImpactReport({
      affectedSpecs: ["auth-spec.md"],
    });

    const report = detectConflicts(impact, tmpDir);

    expect(report.hasConflict).toBe(false);
    expect(report.conflicts).toEqual([]);
  });

  it("detects manually-edited specs as conflicts", () => {
    const modulesDir = path.join(
      tmpDir,
      "openspec",
      "specs",
      "modules",
    );
    fs.mkdirSync(modulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(modulesDir, "auth-spec.md"),
      "# Auth Spec\n\nThis was written by hand.",
      "utf-8",
    );

    const impact = createImpactReport({
      affectedSpecs: ["auth-spec.md"],
    });

    const report = detectConflicts(impact, tmpDir);

    expect(report.hasConflict).toBe(true);
    expect(report.conflicts).toHaveLength(1);
    expect(report.conflicts[0].spec).toBe("auth-spec.md");
    expect(report.conflicts[0].reason).toContain("manual edits");
  });

  it("skips non-existent spec files (no false conflicts)", () => {
    const impact = createImpactReport({
      affectedSpecs: ["non-existent-spec.md"],
    });

    const report = detectConflicts(impact, tmpDir);

    expect(report.hasConflict).toBe(false);
    expect(report.conflicts).toEqual([]);
  });

  it("detects conflicts among multiple specs", () => {
    const modulesDir = path.join(
      tmpDir,
      "openspec",
      "specs",
      "modules",
    );
    fs.mkdirSync(modulesDir, { recursive: true });

    fs.writeFileSync(
      path.join(modulesDir, "auto-spec.md"),
      "Auto-generated by sdd-exoskeleton\n\nContent.",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(modulesDir, "manual-spec.md"),
      "# Manual spec",
      "utf-8",
    );

    const impact = createImpactReport({
      affectedSpecs: ["auto-spec.md", "manual-spec.md"],
    });

    const report = detectConflicts(impact, tmpDir);

    expect(report.hasConflict).toBe(true);
    expect(report.conflicts).toHaveLength(1);
    expect(report.conflicts[0].spec).toBe("manual-spec.md");
  });

  it("returns no conflicts when affectedSpecs is empty", () => {
    const impact = createImpactReport({ affectedSpecs: [] });

    const report = detectConflicts(impact, tmpDir);

    expect(report.hasConflict).toBe(false);
    expect(report.conflicts).toEqual([]);
  });
});
