import * as path from "node:path";

import type { SddConfig } from "../config.js";
import type { ModuleTopology } from "../analyzers/structure.js";
import { safeRead, safeWrite } from "../utils/fs.js";
import { getLanguageConfig } from "../analyzers/language.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface WriteResult {
  written: string[];
  skipped: string[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const AUTO_GEN_MARKER = "Auto-generated by sdd-exoskeleton";

// ---------------------------------------------------------------------------
// generateClaudeMd
// ---------------------------------------------------------------------------

/**
 * Render a CLAUDE.md project constitution.
 *
 * Sections: Project Overview, Tech Stack, Module Map, Coding Standards,
 * and SDD Workflow instructions.
 */
export function generateClaudeMd(
  config: SddConfig,
  topology: ModuleTopology,
): string {
  const lines: string[] = [];

  lines.push(`# ${escapeMd(config.project.name)}`);
  lines.push("");
  lines.push(`> ${AUTO_GEN_MARKER}. Edit with care — changes may be overwritten on next sync.`);
  lines.push("");

  // -- Project Overview --------------------------------------------------------
  lines.push("## Project Overview");
  lines.push("");
  lines.push(
    `${escapeMd(config.project.name)} — ${config.project.languages.join(", ")}`,
  );
  lines.push("");
  lines.push(`**Source:** \`${escapeMd(config.project.srcDir)}\``);
  lines.push(
    `**Languages:** ${config.project.languages.map((l) => `\`${escapeMd(l)}\``).join(", ")}`,
  );
  lines.push("");

  // -- Tech Stack --------------------------------------------------------------
  lines.push("## Tech Stack");
  lines.push("");
  for (const lang of config.project.languages) {
    try {
      const langConfig = getLanguageConfig(lang);
      lines.push(`### ${capitalize(lang)}`);
      lines.push("");
      lines.push(`- **Linter:** \`${escapeMd(langConfig.linter)}\``);
      lines.push(`- **Formatter:** \`${escapeMd(langConfig.formatter)}\``);
      lines.push(`- **Style Guide:** \`${escapeMd(langConfig.styleGuide)}\``);
      lines.push("");
    } catch {
      lines.push(`### ${capitalize(lang)}`);
      lines.push("");
      lines.push("_No tooling configuration available._");
      lines.push("");
    }
  }

  // -- Module Map --------------------------------------------------------------
  lines.push("## Module Map");
  lines.push("");
  if (topology.modules.length > 0) {
    const sorted = [...topology.modules].sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    for (const mod of sorted) {
      lines.push(
        `- **${escapeMd(mod.name)}** — \`${escapeMd(mod.path)}\` (${mod.files.length} files, ${mod.exports.length} exports)`,
      );
    }
  } else {
    lines.push("_No modules indexed yet._");
  }
  lines.push("");

  // -- Coding Standards --------------------------------------------------------
  lines.push("## Coding Standards");
  lines.push("");
  for (const lang of config.project.languages) {
    try {
      const langConfig = getLanguageConfig(lang);
      lines.push(`- **${capitalize(lang)}:** follow \`${escapeMd(langConfig.styleGuide)}\` guidance`);
    } catch {
      lines.push(`- **${capitalize(lang)}:** _no style guide configured_`);
    }
  }
  lines.push("");

  // -- SDD Workflow ------------------------------------------------------------
  lines.push("## SDD Workflow");
  lines.push("");
  lines.push("This project uses Specification-Driven Development (SDD). See:");
  lines.push("");
  lines.push(`- **Specs:** \`${escapeMd(config.openspec.path)}/specs/\``);
  lines.push(`- **Changes:** \`${escapeMd(config.openspec.changeDir)}\``);
  lines.push(`- **SDD Vault:** \`${escapeMd(config.obsidian.vaultPath)}\``);
  lines.push("");

  lines.push("### Commands");
  lines.push("");
  lines.push("- `sdd status` — check SDD health");
  lines.push("- `sdd sync` — sync code changes to specs");
  lines.push("- `sdd doctor` — diagnose integration issues");
  lines.push("");

  lines.push("### Workflow");
  lines.push("");
  lines.push(`1. Propose changes in \`${escapeMd(config.openspec.changeDir)}\``);
  lines.push("2. Implement after spec approval");
  lines.push("3. Archive completed changes");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// generateAgentsMd
// ---------------------------------------------------------------------------

/**
 * Render an AGENTS.md file for OpenCode / AI agent instructions.
 *
 * Includes project context, module structure, SDD commands, and coding rules.
 */
export function generateAgentsMd(
  config: SddConfig,
  topology: ModuleTopology,
): string {
  const lines: string[] = [];

  lines.push(`# ${escapeMd(config.project.name)} — AI Agent Instructions`);
  lines.push("");
  lines.push(`> ${AUTO_GEN_MARKER}`);
  lines.push("");

  // -- Project Context ---------------------------------------------------------
  lines.push("## Project Context");
  lines.push("");
  const langList = config.project.languages
    .map((l) => `\`${escapeMd(l)}\``)
    .join(", ");
  lines.push(`This is a ${langList} project. Source code is in \`${escapeMd(config.project.srcDir)}\`.`);
  lines.push("");

  // -- Module Structure --------------------------------------------------------
  lines.push("## Module Structure");
  lines.push("");
  if (topology.modules.length > 0) {
    const sorted = [...topology.modules].sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    for (const mod of sorted) {
      lines.push(`- **${escapeMd(mod.name)}** — \`${escapeMd(mod.path)}\``);
    }
  } else {
    lines.push("_No modules indexed yet._");
  }
  lines.push("");

  // -- SDD Commands ------------------------------------------------------------
  lines.push("## SDD Commands");
  lines.push("");
  lines.push("Run `sdd` commands to interact with the SDD tooling:");
  lines.push("- `sdd status` — current project state");
  lines.push("- `sdd sync` — sync changes");
  lines.push("- `sdd doctor` — health check");
  lines.push("");

  // -- Coding Rules ------------------------------------------------------------
  lines.push("## Coding Rules");
  lines.push("");
  for (const lang of config.project.languages) {
    try {
      const langConfig = getLanguageConfig(lang);
      lines.push(
        `- **${capitalize(lang)}:** lint with \`${escapeMd(langConfig.linter)}\`, format with \`${escapeMd(langConfig.formatter)}\``,
      );
    } catch {
      lines.push(`- **${capitalize(lang)}:** _no tooling configured_`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// writeConstitution
// ---------------------------------------------------------------------------

/**
 * Write CLAUDE.md and AGENTS.md to the project directory.
 *
 * Existing files are only overwritten if they contain the sdd-exoskeleton
 * auto-generation marker.  Files that exist without the marker are skipped.
 *
 * Returns a result listing which files were written and which were skipped.
 */
export function writeConstitution(
  projectDir: string,
  config: SddConfig,
  topology: ModuleTopology,
): WriteResult {
  const written: string[] = [];
  const skipped: string[] = [];

  const claudePath = path.join(projectDir, "CLAUDE.md");
  const agentsPath = path.join(projectDir, "AGENTS.md");

  const claudeContent = generateClaudeMd(config, topology);
  writeIfAllowed(claudePath, claudeContent, written, skipped);

  const agentsContent = generateAgentsMd(config, topology);
  writeIfAllowed(agentsPath, agentsContent, written, skipped);

  return { written, skipped };
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/**
 * Write content to a file path only if the file does not exist or already
 * contains the auto-generation marker.  Updates the written / skipped lists
 * in place.
 */
function writeIfAllowed(
  filePath: string,
  content: string,
  written: string[],
  skipped: string[],
): void {
  const existing = safeRead(filePath);

  if (existing !== null && !existing.includes(AUTO_GEN_MARKER)) {
    skipped.push(filePath);
    return;
  }

  safeWrite(filePath, content);
  written.push(filePath);
}

/** Escape markdown special characters so raw values render literally. */
function escapeMd(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/</g, "\\<")
    .replace(/>/g, "\\>");
}

/** Capitalize the first character of a string. */
function capitalize(value: string): string {
  if (value.length === 0) return value;
  return value[0].toUpperCase() + value.slice(1);
}
