import * as path from "node:path";

import type { ModuleInfo, DepEdge } from "../integrations/codegraph.js";

import type { ModuleTopology } from "../analyzers/structure.js";
import { safeWrite, mkdirp } from "../utils/fs.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SymbolChange {
  name: string;
  type: "added" | "modified" | "removed" | "renamed";
  module: string;
  summary: string;
  affectedApis: string[];
  affectedModules: string[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const AUTO_GEN_BANNER = "> Auto-generated by sdd-exoskeleton";

const SPECS_DIR = "specs";
const MODULES_DIR = "modules";
const SCHEMAS_DIR = "schemas";

// ---------------------------------------------------------------------------
// generateModuleSpecs
// ---------------------------------------------------------------------------

/**
 * Generate OpenSpec module spec files from a module topology.
 *
 * Each module spec is written as:
 *   <outputDir>/specs/modules/<module.name>.md
 *
 * The spec includes sections for Overview, Classes (stub), API (stub), and
 * Dependencies (populated from topology.edges when available).
 */
export function generateModuleSpecs(
  topology: ModuleTopology,
  outputDir: string,
): void {
  const modulesDir = path.join(outputDir, SPECS_DIR, MODULES_DIR);
  mkdirp(modulesDir);

  for (const mod of topology.modules) {
    const specContent = buildModuleSpec(mod, topology.edges);
    const filePath = path.join(modulesDir, `${mod.name}.md`);
    safeWrite(filePath, specContent);
  }
}

// ---------------------------------------------------------------------------
// generateSchemas
// ---------------------------------------------------------------------------

/**
 * Generate schema stub files.
 *
 * Writes placeholder schema files directly under outputDir:
 *   <outputDir>/schemas/<name>.schema.md
 *   <outputDir>/schemas/README.md
 *
 * Real DB schema extraction from CodeGraph will be wired in a later task.
 */
export function generateSchemas(outputDir: string): void {
  const schemasDir = path.join(outputDir, SCHEMAS_DIR);
  mkdirp(schemasDir);

  // Placeholder schema
  const placeholderContent = buildSchemaPlaceholder("placeholder");
  safeWrite(path.join(schemasDir, "placeholder.schema.md"), placeholderContent);

  // README stub
  const readmeContent = buildSchemasReadme();
  safeWrite(path.join(schemasDir, "README.md"), readmeContent);
}

// ---------------------------------------------------------------------------
// generateChangeProposal
// ---------------------------------------------------------------------------

/**
 * Generate a change proposal markdown file for a given symbol change.
 *
 * The proposal is written to a flat file directly under outputDir:
 *   <outputDir>/proposal.md
 */
export function generateChangeProposal(
  change: SymbolChange,
  outputDir: string,
): void {
  const content = buildChangeProposal(change);
  const filePath = path.join(outputDir, "proposal.md");
  safeWrite(filePath, content);
}

// ---------------------------------------------------------------------------
// Private: module spec builder
// ---------------------------------------------------------------------------

function buildModuleSpec(mod: ModuleInfo, edges: readonly DepEdge[]): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Module: ${mod.name}`);
  lines.push("");
  lines.push(AUTO_GEN_BANNER);
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`${mod.path} — ${mod.files.length} files`);
  lines.push("");

  // Classes (stub)
  lines.push("## Classes");
  lines.push("");
  lines.push("| Class | Description |");
  lines.push("|-------|-------------|");
  lines.push("| _No classes detected_ | |");
  lines.push("");

  // API
  lines.push("## API");
  lines.push("");
  lines.push("| Method/Function | Signature | Description |");
  lines.push("|-----------------|-----------|-------------|");
  if (mod.exports.length > 0) {
    for (const exp of mod.exports) {
      lines.push(`| ${escapePipe(exp)} | | |`);
    }
  } else {
    lines.push("| _No exports detected_ | | |");
  }
  lines.push("");

  // Dependencies
  const moduleDeps = findModuleDependencies(mod.name, edges);
  lines.push("## Dependencies");
  lines.push("");
  if (moduleDeps.length > 0) {
    for (const dep of moduleDeps) {
      lines.push(`- [[${dep}]]`);
    }
  } else {
    lines.push("_No dependencies detected._");
  }
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Private: schema builders
// ---------------------------------------------------------------------------

function buildSchemaPlaceholder(name: string): string {
  const lines: string[] = [];

  lines.push(`# Schema: ${name}`);
  lines.push("");
  lines.push(AUTO_GEN_BANNER);
  lines.push("");
  lines.push("## Table: placeholder");
  lines.push("");
  lines.push("| Column | Type | Nullable | Description |");
  lines.push("|--------|------|----------|-------------|");
  lines.push("| id | TEXT | NO | Primary key |");
  lines.push("| created_at | TIMESTAMP | NO | Creation timestamp |");
  lines.push("");
  lines.push("## Relations");
  lines.push("");
  lines.push("_No relations extracted yet._");
  lines.push("");

  return lines.join("\n");
}

function buildSchemasReadme(): string {
  const lines: string[] = [];

  lines.push("# Schemas");
  lines.push("");
  lines.push(AUTO_GEN_BANNER);
  lines.push("");
  lines.push(
    "This directory contains database schema specifications auto-generated " +
      "from the project's data layer.",
  );
  lines.push("");
  lines.push(
    "Real schema extraction from CodeGraph will be wired in a future task. " +
      "For now, this is a placeholder.",
  );
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Private: change proposal builder
// ---------------------------------------------------------------------------

function buildChangeProposal(change: SymbolChange): string {
  const lines: string[] = [];

  lines.push(`# Change: ${change.name}`);
  lines.push("");
  lines.push(AUTO_GEN_BANNER);
  lines.push("");
  lines.push(`**Type:** ${change.type}`);
  lines.push(`**Module:** ${change.module}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(change.summary);
  lines.push("");

  // Affected Modules
  lines.push("## Affected Modules");
  lines.push("");
  if (change.affectedModules.length > 0) {
    for (const mod of change.affectedModules) {
      lines.push(`- ${mod}`);
    }
  } else {
    lines.push("_No affected modules specified._");
  }
  lines.push("");

  // Affected APIs
  lines.push("## Affected APIs");
  lines.push("");
  if (change.affectedApis.length > 0) {
    for (const api of change.affectedApis) {
      lines.push(`- ${api}`);
    }
  } else {
    lines.push("_No affected APIs specified._");
  }
  lines.push("");

  // Tasks
  lines.push("## Tasks");
  lines.push("");
  lines.push("- [ ] Review impact");
  lines.push("- [ ] Update specs");
  lines.push("- [ ] Update tests");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Private: utilities
// ---------------------------------------------------------------------------

/**
 * Find dependency targets for a given module from the edge list.
 *
 * Returns an array of target module names (deduplicated) that are connected
 * to the given module via an edge where `source` matches the module name.
 */
function findModuleDependencies(
  moduleName: string,
  edges: readonly DepEdge[],
): string[] {
  const deps = new Set<string>();

  for (const edge of edges) {
    if (edge.source === moduleName) {
      deps.add(edge.target);
    }
  }

  return [...deps].sort();
}

/**
 * Escape pipe characters in table cell content so markdown tables render
 * correctly.
 */
function escapePipe(value: string): string {
  return value.replace(/\|/g, "\\|");
}
